### ISSUE TITLE
Footer contains outdated copyright (2016)

### ISSUE THREAD

**Issue by karras** [saltstack/salt-get-started#26]
I couldn't find the code for the footer over at https://docs.saltstack.com/en/getstarted/ anywhere.
It should be updated to 2017. :)

**Comment by waynew** [comment]
Based on https://www.reddit.com/comments/1p9tao and other related information... 2016 is probably fine. If we substantially update/change the site, it's probably fine to update the (C), but in the absence of some compelling legal advise otherwise, I'm happy to leave it as-is.
